
services:
  # MSSQL Docker
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: ebarbershop_db
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    expose:
      - 1433
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - ebarbershop-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP port
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - ebarbershop-net

  ebarbershop_api:
    build:
      context: .
      dockerfile: eBarbershop/Dockerfile
    container_name: ebarbershop_api
    restart: unless-stopped
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=ebarbershopDB;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=true
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7126:80"
    depends_on:
      - db
      - rabbitmq
    networks:
      - ebarbershop-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq_consumer:
    build:
      context: .
      dockerfile: eBarbershop.RabbitMQ/Dockerfile
    container_name: rabbitmq_consumer_container
    restart: unless-stopped
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_HOST=rabbitmq
      - SERVER_ADDRESS=smtp.gmail.com
      - MAIL_SENDER=ebarbershop2024@gmail.com
      - MAIL_PASS=jovbskkfeqscedzn
      - MAIL_PORT=587
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    networks:
      - ebarbershop-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db-data:
  rabbitmq-data:

networks:
  ebarbershop-net:
    driver: bridge