version: '2.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP port
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s  # Give RabbitMQ time to initialize
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  # Persist RabbitMQ data
    networks:
      - ebarbershop-net

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ebarbershop_db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Benaid123!"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s  # Give SQL Server more time to initialize
    networks:
      - ebarbershop-net
    restart: unless-stopped

  ebarbershop_api:
    build:
      context: .
      dockerfile: eBarbershop/Dockerfile
    container_name: ebarbershop_api
    ports:
      - "7126:80"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      CONNECTIONSTRINGS__DEFAULTCONNECTION: "Server=db;Database=benaidfinal;User Id=sa;Password=Benaid123!;TrustServerCertificate=True;MultipleActiveResultSets=true;"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      ASPNETCORE_ENVIRONMENT: Development
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - ebarbershop-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq_consumer:
    build:
      context: .
      dockerfile: eBarbershop.RabbitMQ/Dockerfile
    container_name: rabbitmq_consumer_container
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      SERVER_ADDRESS: smtp.gmail.com
      MAIL_SENDER: ebarbershop2024@gmail.com
      MAIL_PASS: jovbskkfeqscedzn
      MAIL_PORT: 587
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped
    networks:
      - ebarbershop-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db-data:
  rabbitmq-data:

networks:
  ebarbershop-net:
    driver: bridge